/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Meetings */
        get: operations["list_meetings_api_meetings_get"];
        put?: never;
        /** Submit */
        post: operations["submit_api_meetings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{meeting_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meeting */
        get: operations["get_meeting_api_meetings__meeting_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{meeting_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meeting Events */
        get: operations["meeting_events_api_meetings__meeting_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{meeting_id}/summaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rerun Summary */
        post: operations["rerun_summary_api_meetings__meeting_id__summaries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{meeting_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meeting Audio */
        get: operations["meeting_audio_api_meetings__meeting_id__audio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionItemOut */
        ActionItemOut: {
            /** Task */
            task: string;
            /** Owner */
            owner: string | null;
            /** Due */
            due: string | null;
        };
        /** Body_submit_api_meetings_post */
        Body_submit_api_meetings_post: {
            /** File */
            file: string;
            /**
             * Roster
             * @default
             */
            roster: string;
            /**
             * Language
             * @default en
             */
            language: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Provider */
            provider: string;
        };
        /** MeetingDetailOut */
        MeetingDetailOut: {
            meeting: components["schemas"]["MeetingOut"];
            /** Stages */
            stages: components["schemas"]["StageOut"][];
            summary: components["schemas"]["SummaryOut"] | null;
            transcript: components["schemas"]["TranscriptOut"] | null;
        };
        /** MeetingListOut */
        MeetingListOut: {
            /** Meetings */
            meetings: components["schemas"]["MeetingOut"][];
        };
        /** MeetingOut */
        MeetingOut: {
            /** Id */
            id: string;
            /** Filename */
            filename: string;
            /** State */
            state: string;
            /** Language */
            language: string;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Created At */
            created_at: string;
            /** Error */
            error: string | null;
        };
        /** ResummarizeIn */
        ResummarizeIn: {
            /**
             * Language
             * @enum {string}
             */
            language: "en" | "id";
        };
        /** StageOut */
        StageOut: {
            /** Stage */
            stage: string;
            /** Seconds */
            seconds: number;
            /** Model */
            model: string;
            /** Cost Usd */
            cost_usd: number | null;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Detail */
            detail: string;
        };
        /** SubmitOut */
        SubmitOut: {
            /** Id */
            id: string;
        };
        /** SummaryOut */
        SummaryOut: {
            /** Title */
            title: string;
            /** Tldr */
            tldr: string;
            /** Key Points */
            key_points: string[];
            /** Decisions */
            decisions: string[];
            /** Action Items */
            action_items: components["schemas"]["ActionItemOut"][];
            /** Open Questions */
            open_questions: string[];
            /** Language */
            language: string;
            /** Model */
            model: string;
            /** Version */
            version: number;
            /** Repair Attempts */
            repair_attempts: number;
            /** Created At */
            created_at: string;
        };
        /** TranscriptOut */
        TranscriptOut: {
            /** Duration Seconds */
            duration_seconds: number;
            /** Utterances */
            utterances: components["schemas"]["UtteranceOut"][];
        };
        /** UtteranceOut */
        UtteranceOut: {
            /** Start */
            start: number;
            /** Speaker */
            speaker: string;
            /** Text */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_meetings_api_meetings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingListOut"];
                };
            };
        };
    };
    submit_api_meetings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_submit_api_meetings_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_meeting_api_meetings__meeting_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meeting_events_api_meetings__meeting_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rerun_summary_api_meetings__meeting_id__summaries_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResummarizeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meeting_audio_api_meetings__meeting_id__audio_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
}
